Use configuration file for site-specific stuff
Domain and OU are now sourced from a companion configuration file relative to
the msktjoin/adadd scripts

diff --git a/bin/msktjoin b/bin/msktjoin
--- a/bin/msktjoin
+++ b/bin/msktjoin
@@ -4,7 +4,15 @@
 # principle, aka "joins AD Domain"
 #
 
-OU='ou=Workstations,ou=Computers,ou=SciComp'
+# Resolve working directory
+tld=$(dirname(dirname($0)))
+# Locate config relative to script
+cfg=${tld}/etc/msktjoin.cfg
+
+. ${cfg} || ( \
+	echo "ERROR: Config file ${cfg} is not readable- install may be broken" ;\
+	exit 1 ;
+ )
 
 if [ $# -ne 1 ]
 then
@@ -17,7 +25,7 @@ computername=`hostname -s`
 
 if [ "$hostfqdn" = "$computername" ]
 then
-  hostfqdn="${computername}.fhcrc.org"
+  hostfqdn="${computername}.${domain}"
 fi
 
 # add --verbose for debugging
@@ -30,7 +38,7 @@ msktutil --dont-expire-password \
 	--computer-name $computername \
 	--server dc \
 	--enctypes 0x07 \
-	-b "$OU" \
+	-b "${ou}" \
 	-k /etc/krb5.keytab \
 	-h $hostfqdn \
 	-s host/$hostfqdn \
